"""Initial migration

Revision ID: b25a5fa60b7a
Revises: 
Create Date: 2025-10-01 01:55:24.830988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25a5fa60b7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email_from', sa.String(length=255), nullable=True),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_user', sa.String(length=255), nullable=True),
    sa.Column('smtp_pass', sa.Text(), nullable=True),
    sa.Column('twilio_account_sid', sa.String(length=255), nullable=True),
    sa.Column('twilio_auth_token', sa.Text(), nullable=True),
    sa.Column('twilio_from_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_profiles_created_at'), 'notification_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_profiles_name'), 'notification_profiles', ['name'], unique=False)
    op.create_table('trackers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('selector', sa.String(length=1000), nullable=True),
    sa.Column('alert_method', sa.String(length=10), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['notification_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tracker_active_created', 'trackers', ['is_active', 'created_at'], unique=False)
    op.create_index('idx_tracker_method_active', 'trackers', ['alert_method', 'is_active'], unique=False)
    op.create_index(op.f('ix_trackers_alert_method'), 'trackers', ['alert_method'], unique=False)
    op.create_index(op.f('ix_trackers_created_at'), 'trackers', ['created_at'], unique=False)
    op.create_index(op.f('ix_trackers_currency'), 'trackers', ['currency'], unique=False)
    op.create_index(op.f('ix_trackers_is_active'), 'trackers', ['is_active'], unique=False)
    op.create_index(op.f('ix_trackers_last_price'), 'trackers', ['last_price'], unique=False)
    op.create_index(op.f('ix_trackers_profile_id'), 'trackers', ['profile_id'], unique=False)
    op.create_index(op.f('ix_trackers_url'), 'trackers', ['url'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracker_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['tracker_id'], ['trackers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_history_checked_price', 'price_history', ['checked_at', 'price'], unique=False)
    op.create_index('idx_price_history_tracker_checked', 'price_history', ['tracker_id', 'checked_at'], unique=False)
    op.create_index(op.f('ix_price_history_checked_at'), 'price_history', ['checked_at'], unique=False)
    op.create_index(op.f('ix_price_history_price'), 'price_history', ['price'], unique=False)
    op.create_index(op.f('ix_price_history_tracker_id'), 'price_history', ['tracker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_tracker_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_price'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_checked_at'), table_name='price_history')
    op.drop_index('idx_price_history_tracker_checked', table_name='price_history')
    op.drop_index('idx_price_history_checked_price', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_trackers_url'), table_name='trackers')
    op.drop_index(op.f('ix_trackers_profile_id'), table_name='trackers')
    op.drop_index(op.f('ix_trackers_last_price'), table_name='trackers')
    op.drop_index(op.f('ix_trackers_is_active'), table_name='trackers')
    op.drop_index(op.f('ix_trackers_currency'), table_name='trackers')
    op.drop_index(op.f('ix_trackers_created_at'), table_name='trackers')
    op.drop_index(op.f('ix_trackers_alert_method'), table_name='trackers')
    op.drop_index('idx_tracker_method_active', table_name='trackers')
    op.drop_index('idx_tracker_active_created', table_name='trackers')
    op.drop_table('trackers')
    op.drop_index(op.f('ix_notification_profiles_name'), table_name='notification_profiles')
    op.drop_index(op.f('ix_notification_profiles_created_at'), table_name='notification_profiles')
    op.drop_table('notification_profiles')
    # ### end Alembic commands ###
